import Head from 'next/head';

export default function Home() {
  async function deleteUser(id) {
    const res = await fetch(`${process.env.NEXT_PUBLIC_APP_BASE_URL}/api/delete-user?user=${id}`);
    const data = await res.json();

    if (res.status !== 200) {
      console.error('Error calling delete user api', { status: res.status, statusText: res.statusText, data });
      return;
    }

    console.log('Deleted user', data);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>Delete a user from supabase</h1>
        <br />
        <button onClick={() => deleteUser('test-user-id')}>Delete user with id "test-user-id"</button>
      </main>
    </>
  );
}
